=== Steve2404/spring-start-here/base/xml-kurse/src/main/resources/vorkurs02_xml/fixtures/ex05/catalog.dtd
<!ELEMENT catalog (section+)>
<!ELEMENT section (heading, (item | bundle)*, note?)>
<!ELEMENT heading (#PCDATA)>
<!ELEMENT item    (name, price, (tag, tag?)?)>
<!ELEMENT bundle  (item, item+)>
<!ELEMENT name    (#PCDATA)>
<!ELEMENT price   (#PCDATA)>
<!ELEMENT tag     (#PCDATA)>
<!ELEMENT note    (#PCDATA | b | i)*>
<!ELEMENT b       (#PCDATA)>
<!ELEMENT i       (#PCDATA)>
<!ELEMENT br      EMPTY>
<!ELEMENT extra   ANY>

=== Steve2404/spring-start-here/base/xml-kurse/src/main/resources/vorkurs02_xml/fixtures/ex05/03-three-tags.xml
<?xml version="1.0"?>
<!DOCTYPE catalog SYSTEM "catalog.dtd">
<catalog>
  <section>
    <heading>Tags</heading>
    <item><name>A</name><price>1</price><tag>x</tag><tag>y</tag><tag>z</tag></item>
  </section>
</catalog>

=== Steve2404/spring-start-here/base/xml-kurse/src/main/resources/vorkurs02_xml/fixtures/ex05/01-valid.xml
<?xml version="1.0"?>
<!DOCTYPE catalog SYSTEM "catalog.dtd">
<catalog>
  <section>
    <heading>Papeterie</heading>
    <item><name>Stylo</name><price>2</price></item>
    <bundle>
      <item><name>Gomme</name><price>1</price><tag>eco</tag></item>
      <item><name>Regle</name><price>3</price><tag>bois</tag><tag>30cm</tag></item>
    </bundle>
    <note>Livraison <b>gratuite</b> des <i>50</i> euros</note>
  </section>
  <section>
    <heading>Vide</heading>
  </section>
</catalog>
